<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>.

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("users/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("users/new", "Create ")); ?>
        </td>
    </tr>
</table>

<!--<table class="browse" align="center">-->
<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
    <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Password</th>
            <th>Nick</th>
            <th>Email</th>
            <th>Created</th>
            <th>Modified</th>
            <th>Timezone</th>
            <th>Is Of Banned</th>
            <th>Status</th>
            <th>Is Of Deleted</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $user) { ?>
        <tr>
            <td><?= $user->id ?></td>
            <td><?= $user->username ?></td>
            <td><?= $user->password ?></td>
            <td><?= $user->nick ?></td>
            <td><?= $user->email ?></td>
            <td><?= $user->created_at ?></td>
            <td><?= $user->modified_at ?></td>
            <td><?= $user->timezone ?></td>
            <td><?= $user->is_banned ?></td>
            <td><?= $user->status ?></td>
            <td><?= $user->is_deleted ?></td>
            <td><?php echo $this->tag->linkTo(array("users/edit/" . $user->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("users/delete/" . $user->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
<!--                        <td>--><?php //echo $this->tag->linkTo("users/search", "First") ?><!--</td>-->
                        <td><?= Phalcon\Tag::linkTo("users/search")?></td>
                        <td><?php echo $this->tag->linkTo("users/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("users/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("users/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
